### ISSUE TITLE
Fix another robustness issue

### ISSUE THREAD

**Issue by PanderMusubi** [Sinap/kodiswift#19]
The fix https://codecov.io/gh/Sinap/kodiswift/compare/8d715c01091da3952d8eb625420889732e5b4b84...18184ee1072af31726ed43a4740e57ed3adc79a4?src=pr from https://github.com/Sinap/kodiswift/pull/6 fixed one part. But there is still an issue with another part of the code.

The error is:

```
22:49:02 T:140138852108032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                        Error Type: <type 'exceptions.AttributeError'>
                                        Error Contents: 'list' object has no attribute 'as_tuple'
                                        Traceback (most recent call last):
                                          File "/home/sander/.kodi/addons/plugin.video.intergalacticfm/addon.py", line 168, in <module>
                                            plugin.run()
                                          File "/home/sander/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 307, in run
                                            items = self._dispatch(self.request.path)
                                          File "/home/sander/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 335, in _dispatch
                                            resp = self.finish(items=resp)
                                          File "/home/sander/.kodi/addons/script.module.kodiswift/lib/kodiswift/xbmcmixin.py", line 471, in finish
                                            self.add_items(items)
                                          File "/home/sander/.kodi/addons/script.module.kodiswift/lib/kodiswift/xbmcmixin.py", line 384, in add_items
                                            tuples = [item.as_tuple() for item in _items]
                                        AttributeError: 'list' object has no attribute 'as_tuple'
                                        -->End of Python script error report<--
```

The line https://github.com/Sinap/kodiswift/blob/master/kodiswift/xbmcmixin.py#L384 may only work for whem item is really a tuple. Fixing this will help at least three plugins that are/were using xbmcswift2 before and migrate to kodiswift.

**Comment by PanderMusubi** [comment]
Probably the fix needs to be something similar to:

```
tuples = [item.as_tuple() for item in _items if hasattr(item, 'as_tuple')]
```

**Comment by afrase** [comment]
Thanks for the contribution.

I'm not sure the item should be silently dropped but to do things properly would probably require rewriting a lot of code. If you want to make that fix and submit a pull request I'll merge it, if not I'll try to get to it this weekend.

**Comment by PanderMusubi** [comment]
I tested it and it works

**Comment by afrase** [comment]
Fixed with pull request #20

**Comment by PanderMusubi** [comment]
I see you made a version 0.0.6 (without bugging) any idea when this will be in kodi? http://mirrors.kodi.tv/addons/jarvis/script.module.kodiswift/

**Comment by PanderMusubi** [comment]
Please, offer 0.0.6 to KODI so my plugins get updated there too. Thanks

**Comment by PanderMusubi** [comment]
Well, 0.0.7 now of course :-)
